name: workflow

on: push

jobs:
  first:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Welcome message
        run: echo "Hello"

      - name: List files
        run: ls

      - name: Read README.md
        run: cat README.md

    

